sudo: required
services:
  - docker

before_install:
  - docker build -t afankhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true afankhan/react-test npm test

after_success:
  - docker build -t afankhan/multi-client ./client
  - docker build -t afankhan/multi-nginx ./nginx
  - docker build -t afankhan/multi-server ./server
  - docker build -t afankhan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take above images and push them to docker hub
  - docker push afankhan/multi-client
  - docker push afankhan/multi-nginx
  - docker push afankhan/multi-server
  - docker push afankhan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-661815601808
  bucketpath: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY